variable "vpc_cidr" {}
variable "az1" {}
variable "cidr-pub-01" {}
variable "az2" {}
variable "cidr-pub-02" {}
variable "cidr-prt-1" {}
variable "cidr-prt-2" {}
variable "cidr-pub-RT" {}
variable "port_ssh" {}
variable "port_http" {}
variable "port_https" {}
variable "ami" {}
variable "instance_type" {}
